### ISSUE TITLE
青龙运行weibo_chaohua_sign.py日志为空，实际没有运行成功

### ISSUE THREAD

**Issue by ChampionChann** [kuku3863/sign_weibo_chaohua#14]
今天本该自动运行的签到任务，收到推送时，签到结果列表为空，今天刚出现的问题，抓的是cardlist请求连接，已尝试重新抓包还是一样
![image](https://github.com/user-attachments/assets/3b414faa-2211-46d5-972e-cb0786b519c4)

**Comment by kuku3863** [comment]
> 今天本该自动运行的签到任务，收到推送时，签到结果列表为空，今天刚出现的问题，抓的是cardlist请求连接，已尝试重新抓包还是一样 ![image](https://private-user-images.githubusercontent.com/74972604/354433726-3b414faa-2211-46d5-972e-cb0786b519c4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTM3NDIsIm5iZiI6MTcyMjU5MzQ0MiwicGF0aCI6Ii83NDk3MjYwNC8zNTQ0MzM3MjYtM2I0MTRmYWEtMjIxMS00NmQ1LTk3MmUtY2IwNzg2YjUxOWM0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxMDEwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYThlYjRhNjA0MTA0Njg1MDk0NjE5YjU3MzM3ZTgzNmJjYmNjZjU4MDVhYjI5MjYzZTU0NDg4MzkyMDgzOWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VlYYk_6LbXISxNIbGQ0aidirL3ngb_yjaN5A125X3dg)

这种情况会不会是在之前运行过一次？因为我这代码是不够严谨的，后续我加一些返回值的判断，目前你这个图的情况，我遇到的是之前手动运行过一次，再次运行就会出现这样

**Comment by ChampionChann** [comment]
> > 今天本该自动运行的签到任务，自动运行时，签到结果列表为空，今天刚出现的问题，抓的是cardlist请求连接，已尝试重新抓包还是一样![图像](https://private-user-images.githubusercontent.com/74972604/354433726-3b414faa-2211-46d5-972e-cb0786b519c4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTM3NDIsIm5iZiI6MTcyMjU5MzQ0MiwicGF0aCI6Ii83NDk3MjYwNC8zNTQ0MzM3MjYtM2I0MTRmYWEtMjIxMS00NmQ1LTk3MmUtY2IwNzg2YjUxOWM0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxMDEwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYThlYjRhNjA0MTA0Njg1MDk0NjE5YjU3MzM3ZTgzNmJjYmNjZjU4MDVhYjI5MjYzZTU0NDg4MzkyMDgzOWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VlYYk_6LbXISxNIbGQ0aidirL3ngb_yjaN5A125X3dg)
> 
> 这种情况不会再次出现在运行过一次之前吗？因为我这个代码不够严谨的，后续我加了一些返回值的判断，目前你这个图的情况，我遇到的是手动运行过一次之前，运行就会出现这样


我是通过定时任务每天自动运行一次，在自动运行之前我没有进行手动运行，我发现了日志更多的细节，这可能是造成出错的原因：

## 开始执行... 2024-08-02 09:56:50

超话列表：


签到结果：

serverJ 服务启动
tg 服务启动
serverJ 推送成功！
    sock = connection.create_connection(
           ^^^^^^^^^    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
Exception in thread telegram_bot:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 196, in _new_conn
^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f122a03c890>, 'Connection to api.telegram.org timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6910647222:AAHj4spVRhM2vtzbeWfyIQYG84_r3YIXZmo/sendMessage?chat_id=1729302732&text=%E5%BE%AE%E5%8D%9A%E7%AD%BE%E5%88%B0%E7%BB%93%E6%9E%9C%3A%0A%0A%E8%B6%85%E8%AF%9D%E5%88%97%E8%A1%A8%EF%BC%9A%0A%0A%0A%E7%AD%BE%E5%88%B0%E7%BB%93%E6%9E%9C%EF%BC%9A%0A%0A%0A%E8%87%AA%E5%B7%B1%E7%9A%84%E7%97%9B%E8%8B%A6%E5%88%AB%E4%BA%BA%E6%97%A0%E6%B3%95%E7%90%86%E8%A7%A3%E3%80%82++++----%E4%B8%89%E8%89%B2%E7%BB%98%E6%81%8Bs&disable_web_page_preview=true (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f122a03c890>, 'Connection to api.telegram.org timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/ql/data/scripts/kuku3863_sign_weibo_chaohua_master/notify.py", line 601, in telegram_bot
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 115, in post
return request("post", url, data=data, json=json, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6910647222:AAHj4spVRhM2vtzbeWfyIQYG84_r3YIXZmo/sendMessage?chat_id=1729302732&text=%E5%BE%AE%E5%8D%9A%E7%AD%BE%E5%88%B0%E7%BB%93%E6%9E%9C%3A%0A%0A%E8%B6%85%E8%AF%9D%E5%88%97%E8%A1%A8%EF%BC%9A%0A%0A%0A%E7%AD%BE%E5%88%B0%E7%BB%93%E6%9E%9C%EF%BC%9A%0A%0A%0A%E8%87%AA%E5%B7%B1%E7%9A%84%E7%97%9B%E8%8B%A6%E5%88%AB%E4%BA%BA%E6%97%A0%E6%B3%95%E7%90%86%E8%A7%A3%E3%80%82++++----%E4%B8%89%E8%89%B2%E7%BB%98%E6%81%8Bs&disable_web_page_preview=true (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f122a03c890>, 'Connection to api.telegram.org timed out. (connect timeout=None)'))

## 执行结束... 2024-08-02 09:59:04  耗时 134 秒

**Comment by uwhatsup** [comment]
同样的问题 空白
